name = "orange-meets-public"

account_id = "7829299e6cefc232ded8635f50b53462"
main = "build/index.mjs"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-10-07"
compatibility_flags = ["nodejs_compat"]

[site]
  bucket = "./public"

[vars]
CALLS_APP_ID = "1ff13ac8f27014b77f7eb5bc178aceae"
CALLS_API_URL = "https://rtc.live.cloudflare.com/v1"
TURN_SERVICE_ID = "46711d6c5759085dd70f599f6190ab94"
PUBLIC = "true"
BACKGROUND_IMAGE_URL = ""

[[durable_objects.bindings]]
name = "rooms"
class_name = "ChatRoom"

# Indicate that you want the ChatRoom and RateLimiter classes to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ChatRoom", "RateLimiter"]

[[migrations]]
tag = "v2"
deleted_classes = ["RateLimiter"] 

# The necessary secrets are:
# - CALLS_APP_SECRET
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these


