name = "orange-meets"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2025-01-01"
main = "build/index.mjs"
compatibility_flags = ["nodejs_compat"]
account_id = "7829299e6cefc232ded8635f50b53462"

[site]
  bucket = "./public"

[vars]
CALLS_APP_ID = "bf67b659a7dad4da746fffcaa8e3ac56"
CALLS_API_URL = "https://rtc.live.cloudflare.com/v1"
TURN_SERVICE_ID = "d47b72813b70550b4e4724c25afa85a0"
BACKGROUND_IMAGE_URL = "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=2564&auto=format&fit=crop"

MAX_WEBCAM_BITRATE=8500000
MAX_WEBCAM_FRAMERATE=60
MAX_WEBCAM_QUALITY_LEVEL=1080

ENABLE_WORKERS_AI = "false"

[[d1_databases]]
binding = "DB"
database_name = "orange-meets-db"
database_id = "722818b7-63af-4395-bad1-c68ce86d2bd4"

[ai]
binding = "AI"

# Optional vars
# OPENAI_MODEL_ENDPOINT = ""

[[durable_objects.bindings]]
name = "rooms"
class_name = "ChatRoom"

# Indicate that you want the ChatRoom class to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_sqlite_classes = ["ChatRoom"]

# The necessary secrets are:
# - CALLS_APP_SECRET
# To add secret, run `echo <VALUE> | wrangler secret put <NAME>`

# Optional secrets:
# OPENAI_API_TOKEN = ""