name = "orange-meets-staging"

account_id = "7829299e6cefc232ded8635f50b53462"
main = "build/index.mjs"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-10-07"
compatibility_flags = ["nodejs_compat"]

[[durable_objects.bindings]]
name = "rooms"
class_name = "ChatRoom"

[vars]
CALLS_APP_ID = "9effffd0c077c1115c7d285e55593a9a"
CALLS_API_URL = "https://rtc.live.cloudflare.com/v1"
TURN_SERVICE_ID = "11cebcf8429b947a48c6894650daa021"
EXPERIMENTAL_SIMULCAST_ENABLED = "true"
BACKGROUND_IMAGE_URL = ""

[[queues.producers]]
 queue = "orange-meets-feedback-queue-staging"
 binding = "FEEDBACK_QUEUE"

[[queues.consumers]]
 queue = "orange-meets-feedback-queue-staging"
 # Required: this should match the name of the queue you created in step 3.
 # If you misspell the name, you will receive an error when attempting to publish your Worker.
 max_batch_size = 10 # optional: defaults to 10
 max_batch_timeout = 5 # optional: defaults to 5 seconds

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "orange-meets-db-staging"
database_id = "9f133e78-1a4e-49ad-967a-10fbdc3e1a29"

# Indicate that you want the ChatRoom and RateLimiter classes to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["ChatRoom", "RateLimiter"]

[[migrations]]
tag = "v2"
deleted_classes = ["RateLimiter"] 

[observability]
enabled = true

# The necessary secrets are:
# - CALLS_APP_SECRET
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these


